on: [workflow_dispatch]
name: Pipeline
jobs:
  Login:
    outputs:
      aws_password: ${{ steps.get_password.outputs.password }}
    runs-on: ubuntu-20.04
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2.2.0
        with:
          role-to-assume: ${{secrets.AWS_QA_ROLE}}
          aws-region: ap-northeast-1
      - name: Get AWS password
        id: get_password
        run: echo "password=$(aws ecr get-login-password --region ap-northeast-1)" >> $GITHUB_OUTPUT

  Pipeline:
    needs: Login
    strategy:
      matrix:
        go-version: [ 1.18.5 ]
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: get_tag
        id: get_tag
        run: |
          git fetch --tags
          tag=$(git describe --tags `git rev-list --tags --max-count=1`)
          echo "tag=$tag" >> $GITHUB_OUTPUT
      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: 545408478668.dkr.ecr.ap-northeast-1.amazonaws.com/test_nick

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          tags: 545408478668.dkr.ecr.ap-northeast-1.amazonaws.com/test_nick:$tag
          push: true
