name: Config Checker
on:
  pull_request:
    branches: [ "main" ]
    paths:
      - config.yaml

jobs:
  config_checker:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: pre commit check
        run: |
            if ! command -v pre-command > /dev/null 2>&1; then
                echo "install pre-commit..."
                python -m pip install pre-commit
            fi

            pre-commit run
            if [ $? != 0 ]; then
              exit 1
            else
              exit 0
