on: [push]
name: Echo Secrets Demo
jobs:
  GetSecrets:
    runs-on: ubuntu-20.04
    steps:
      - name: get_secrets
        run: |
            base64_secrets=`echo ${{secrets.ALEX_TEST_SECRETS}} | base64`
            echo $base64_secrets