name: Auto Build & Push To Amazon ECR

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: paulhatch/semantic-version@v4.0.2
        if: github.ref == 'refs/heads/main'
        id: semver
        with:
          tag_prefix: "v"
          major_pattern: "BREAKING CHANGE:"
          minor_pattern: "feat:"
          format: "${major}.${minor}.${patch}"
          short_tags: false
          bump_each_commit: true
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag_prefix: ""
          custom_tag: ${{ steps.semver.outputs.version_tag }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Configure AWS Credentials
        if: github.ref == 'refs/heads/main'
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::545408478668:role/ghe-test-role
          aws-region: ap-northeast-1
      - name: Login to Amazon ECR Private
        if: github.ref == 'refs/heads/main'
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: pull_wallet_core
        if: github.ref == 'refs/heads/main'
        run: |
          docker pull 545408478668.dkr.ecr.ap-northeast-1.amazonaws.com/tssqa-qa-github-walletcore:v4.2.0
          docker tag 545408478668.dkr.ecr.ap-northeast-1.amazonaws.com/tssqa-qa-github-walletcore:v4.2.0 545408478668.dkr.ecr.ap-northeast-1.amazonaws.com/test_nick:v1.1.0

      - name: push_test_image
        if: github.ref == 'refs/heads/main'
        run: |
            docker push 545408478668.dkr.ecr.ap-northeast-1.amazonaws.com/test_nick:v1.1.0
            