on: [workflow_dispatch]
name: manual push to qa
jobs:
  Pipeline:
    runs-on: ubuntu-22.04
    permissions:
      id-token: write
      contents: read

    steps:

      - name: Configure AWS Credentials
        if: github.ref == 'refs/heads/main'
        uses: aws-actions/configure-aws-credentials@v2.2.0
        with:
          role-to-assume: ${{ secrets.AWS_QA_ROLE }}
          aws-region: ap-northeast-1
      - name: Login to Amazon ECR Private
        if: github.ref == 'refs/heads/main'
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
  

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: get_tag
        id: get_tag
        run: |
          git fetch --tags
          tag=$(git describe --tags --exact-match)
          echo "latest_tag=${tag}"
          echo "tag=${tag}" >> $GITHUB_OUTPUT
      - name: get_epoch
        id: get_epoch
        run: |
          epoch=$(git show -s --format=%ct HEAD)
          echo "epoch=${epoch}" >> $GITHUB_OUTPUT
      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: 545408478668.dkr.ecr.ap-northeast-1.amazonaws.com/github-alextest
          tags: type=raw,value=${{ steps.get_tag.outputs.tag }}