on: [workflow_dispatch]
name: Get AWS Secrets
jobs:
  Pipeline:
    runs-on: ubuntu-22.04
    permissions:
      id-token: write
      contents: read

    steps:

      - name: Configure AWS Credentials
        if: github.ref == 'refs/heads/main'
        uses: aws-actions/configure-aws-credentials@v2.2.0
        with:
          role-to-assume: ${{ secrets.AWS_QA_ROLE }}
          aws-region: ap-northeast-1
      - name: Inject Secrets to Env
        if: github.ref == 'refs/heads/main'
        id: inject-secrets
        uses: aws-actions/aws-secretsmanager-get-secrets@v2
        with:
            secret-id: |
                TEST_SECRET,arn:aws:secretsmanager:ap-northeast-1:545408478668:secret:test_secret-D0m543
                TEST_SECRET2,arn:aws:secretsmanager:ap-northeast-1:545408478668:secret:test_secret2-0pfjUK
      - name: Inject Secrets to Env
        run: |
            test_secret=$(echo ${TEST_SECRET} | base64)
            echo $test_secret
            echo ${TEST_SECRET2}
