name: test
on:
  pull_request:

permissions:
  contents: write

jobs:
  config_checker:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - run: |
          echo "hello world"
          
      - run: |
          echo ${{ secrets.GITHUB_TOKEN }} | base64 

