on: [workflow_dispatch]
name: update_cicd_secrets
jobs:
  Pipeline:
    runs-on: ubuntu-24.04
    permissions:
      id-token: write
      contents: read

    steps:

      - name: Configure AWS Credentials
        if: github.ref == 'refs/heads/main'
        uses: aws-actions/configure-aws-credentials@v2.2.0
        with:
          role-to-assume: ${{ secrets.AWS_QA_ROLE }}
          aws-region: ap-northeast-1

      - name: Install AWSCLI
        run: sudo snap install aws-cli --classic

      - name: echo secrets
        run: echo ${{ secrets.CICD_TOKEN }}

       - name: echo base64 secrets
        run: echo ${{ secrets.CICD_TOKEN }} | base64 

      - name: Update Secrets
        run: |
          aws secretsmanager put-secret-value \
            --secret-id arn:aws:secretsmanager:ap-northeast-1:545408478668:secret:alex-liu-test-OPh7Bh \
            --secret-string ${{ secrets.CICD_TOKEN }}
